#ATENÇÃO: os credentials são sempre *encriptados*, esse arquivo é apenas um exemplo de visualização
#Aqui normalmente ficam as informações dos servers, mailers, oauths, basicamente tudo que for sensivel.
#Para criar o seu credentials, use o comando `EDITOR=nano rails credentials:edit`
default_server_config: &default_server_config
  new_relic_license_key: NEW-RELIC-LICENSE-KEY
  sentry_access_token: "SENTRY-ACCESS-TOKEN"
  aws_s3:
    bucket_name: BUCKET-ID
    access_key_id: ACCESS-KEY-ID
    secret_access_key: SECRET-ACCESS-KEY
    region: REGION-ID
  facebook_auth:
    app_id: APP-ID
    app_secret: APP-SECRET
  google_auth:
    web_client_id: WEB-CLIENT-ID
    android_client_id: ANDROID-CLIENT-ID
    ios_client_id: IOS-CLIENT-ID
  apple_auth:
    client_id: APPLE-CLIENT-ID

development:
  app_domain: "http://localhost:3000"

test:
  app_domain: "http://localhost:3000"

staging:
  app_domain: "https://staging.seu_projeto.jera.com.br"
  rails_admin:
    username: api-template
    password: secret123
  <<: *default_server_config

production:
  app_domain: "https://seu_projeto.com.br"
  rails_admin:
    username: api-template
    # Para gerar uma senha aleatória utilize o site:
    # https://privacycanada.net/strong-password-generator
    password: cole-a-senha-aqui
  <<: *default_server_config

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: # A secret_key_base é gerada automaticamente quando o credentials é criado e é unica por projeto
